### PR TITLE
Fix related record filtering/fix union resolution

### LINKED ISSUE #16: Resolver Ignores Subfield Values
First of all, thanks for the great library! 

I was using it to mock results from a search query but I encountered what looks like a bug. 

To give some context, the query that I'm trying to mock takes in a string, here is what my schema looks like:

```graphql
type Dog {
// ... dogfields
}

type Cat {
//... cat fields
}
union Animal = Cat | Dog

type SearchResult {
item: Animal!
rank: Int!
}

type Query {
search(str: String!): [SearchResult!]!
}
```

Whatever I return as `item` from the `search` resolver, Mirage just ignores it and returns the first `Animal` in the database.

I've put together an example repo here: https://github.com/Gamaranto/miragegraphqlbug 
In the example repo, I return `null` as `item` in the `search` resolver, but the first animal in the db is returned anyway.

Thanks in advance for the help!

### LINKED ISSUE #18: The built-in union type resolver doesn't consider parent records
When resolving all types except for union types, the library looks for field values on the parent object, if it's passed in to the resolver. This means resolving fields with a union type only works at the upper most query level or just coincidentally.

The union type resolver needs to be updated to consider the optional parent object.

### LINKED ISSUE #19: Associated records are not filtered by query arguments
When fetching records at the root query level, we use query arguments to filter records from Mirage's database, by default. This is done via Mirage's API. That said, when we resolve associated records we don't consider query arguments.

Pretty much all resolvers need to be updated to properly filter associated records on parent objects.

### PR DESCRIPTION
**Pull request by jneurock**
This PR fixes somewhat related issues #18 and #19 where, respectively, union type resolution can fail when there's a parent object and filtering for related has-many records fails.

A function to filter related records was added and is now called when resolving list types and a list of union types.

Additionally, the type name parameter was removed from the functions that adapt records as this is essentially already present on the record from Mirage's database and doesn't need to be passed in.

Fixes #16.
Fixes #18.
Fixes #19.

### CODE REVIEW

File: lib/utils.js [hunk 1]
```diff
@@ -7,6 +7,17 @@ import {
...
 } from "graphql";
 
+/**
+ * Capitalize a string
+ *
+ * @function capitalize
+ * @param {String} str
+ * @returns {String} The capitalized string.
+ */
+export function capitalize(str) {
```
Comment (jneurock) [inline lib/utils.js:17]: Not to self: May as well test this.

File: lib/resolvers/relay.js [hunk 2]
```diff
@@ -23,7 +23,7 @@ export function resolveRelayConnection(obj, args, context, info, type) {
   const { type: nodeType } = unwrapType(edgeType.getFields().node.type);
   const records =
     obj && obj[info.fieldName] && obj[info.fieldName].models
-      ? adaptRecords(obj[info.fieldName].models, nodeType.name)
+      ? adaptRecords(obj[info.fieldName].models)
```
Comment (jneurock) [inline lib/resolvers/relay.js:26]: Note to self: Double check that these records don't need to be filtered by the GraphQL args.
