### PR TITLE
Fix for resolving non-list union types

### LINKED ISSUE #12: Support for object union types
Hey there and thanks for the awesome library!

I'm running into a problem trying to use a schema with a union type. Consider the following schema:

```graphql
type Orange {
  id: ID!
  weight: Float!
}

type Apple {
  id: ID!
  radius: Float!
}

union Fruit = Orange | Apple

type Basket {
  id: ID!
  fruit: Fruit!
}

type Query {
  basket: Basket!
}
```

I'm trying to run a following query against it:

```graphql
query GetBasket {
  basket {
    id
    fruit {
      ... on Orange {
        id
        weight
      }
      ... on Apple {
        id
        radius
      }
    }
  }
}
```

However, when executing it, I run into an error: `Abstract type "Fruit" must resolve to an Object type at runtime for field "Basket.fruit" with value [{ id: "appleID", radius: 5, __typename: "Apple" }], received "undefined". Either the "Fruit" type should provide a "resolveType" function or each possible type should provide an "isTypeOf" function.`

As can be seen in the error message, the object contains `__typename` field so I'd expect the server to be able to determine the type.

I'm not sure whether that's an issue with the library or me using GraphQL incorrectly but I've tried everything that came to my mind.

### PR DESCRIPTION
**Pull request by jneurock**
This PR fixes an issue where Mirage GraphQL assumes any union type field should resolve to a list. Fixes #12.

### CODE REVIEW

File: lib/resolvers/union.js [hunk 1]
```diff
@@ -9,14 +9,16 @@ import { getRecords } from "../orm/records";
...
  */
-export default function resolveUnion(_obj, args, context, _info, type) {
+export default function resolveUnion(_obj, args, context, _info, isList, type) {
   const types = type.getTypes();
   const recordsForTypes = types.reduce(function (records, type) {
     return [...records, ...getRecords(type, args, context.mirageSchema)];
   }, []);
 
-  return recordsForTypes;
+  return isList ? recordsForTypes : recordsForTypes[0];
```
Comment (kdembler) [inline lib/resolvers/union.js:23]: Would `undefiend` being returned here break things if `recordsForTypes` returns an empty list?

Comment (jneurock) [reply lib/resolvers/union.js:23]: It shouldn't. If the field is required then yes but GraphQL should handle that and give you an appropriate error.
